build:
	cd HelloWorld && make
	cd Generator && make
	cd string && make
	cd vector && make
	cd thread && make
	cd map && make
	cd mutex && make
	cd atomic && make
	cd memory_order && make
	cd unique_ptr && make
	cd sort && make

clean:
	cd HelloWorld && make clean
	cd Generator && make clean
	cd string && make clean
	cd vector && make clean
	cd thread && make clean
	cd map && make clean
	cd mutex && make clean
	cd atomic && make clean
	cd memory_order && make clean
	cd unique_ptr && make clean
	cd sort && make clean
