build:
	cd HelloWorld && make
	cd Generator && make
	cd string && make
	cd vector && make
	cd thread && make
	cd map && make
	cd mutex && make

clean:
	cd HelloWorld && make clean
	cd Generator && make clean
	cd string && make clean
	cd vector && make clean
	cd thread && make clean
	cd map && make clean
	cd mutex && make clean
